### ISSUE TITLE
DbfFileException should be renamed to DbfException,

### ISSUE THREAD

**Issue by nickolanack** [muka/ShapeReader#4]
DbfFileException is never thrown, but DbfFile.php throws DbfException on line 65, so I assume DbfFileException should in fact be DbfException and DbfException.php renamed DbfFileException.php

**Comment by muka** [comment]
Good catch! Can you provide a PR please?

**Comment by nickolanack** [comment]
hmm, I could rename the file to match the exception thrown, DbfFileException.php to DbfException.php, or i could replace the actual exception thrown (throw DbfException) with throw DbfFileException. I think that the later would be preferred. thoughts?

**Comment by muka** [comment]
Both are ok for me, choose the one that looks better for you

Thanks!

2015-05-20 19:01 GMT+02:00 Nick Blackwell <notifications@github.com>:

**Comment by nickolanack** [comment]
Ok, cool. I created a pull request for you.

**Comment by muka** [comment]
Excellent, merged!
