### ISSUE TITLE
M/Z feature type support (unit tests)

### ISSUE THREAD

**Issue by nickolanack** [muka/ShapeReader#6]
I've added support for all the missing feature types (in nickolanack fork), 

        11 => "RecordPointZ",
        13 => "RecordPolyLineZ",
        15 => "RecordPolygonZ",
        18 => "MultiPointZ",
        21 => "PointM",
        23 => "PolyLineM",
        25 => "PolygonM",
        28 => "MultiPointM"

except for  28=>MultiPatch...//I have not implemented this

I would like to submit a pull request, however I don't have any non private .shp files containing these types so I was hoping that it might be possible for someone to compile some in the tests folder, I think the current worldcities.shp only contains x, y feature types.

**Comment by muka** [comment]
Hi, thank you
I do not have idea of where to find a proper shp file to include for testing.

If you want to provide a pull request I'll be happy to check and merge it, I'll add tests later .. hopefully :)

**Comment by nickolanack** [comment]
I'll try to find some shape files (containing m and z type features) myself before I submit a pull request. I also implemented the MultiPatch feature recently, so once I have some tests, I will PR.

**Comment by muka** [comment]
It's a nice set of feature, great work!

**Comment by coreation** [comment]
Hey @nickolanack any idea on when you'll test this feature? I have a shapefile with Z features, if you don't have the time I can test your fork.

**Comment by nickolanack** [comment]
sorry I haven't been able to spend any time on this. It would be amazing if you did that.
Nick

**Comment by coreation** [comment]
I currently have only 1 shapefile with a Z feature, any links to an M shapefile dataset? How did you test your code when you were working on it?

**Comment by nickolanack** [comment]
I added a travis.yml file to my fork, and automated testing on my git repo at https://travis-ci.org/nickolanack/ShapeReader (Although this only ran the original unit tests) Unfortunately, I do not have any shapefiles with those features that I can publish.

**Comment by nickolanack** [comment]
Do you want me to submit a pull request?

**Comment by coreation** [comment]
Yea that would be ok by me, I have at least one file that includes Z coordinates. Not sure how this repository works in terms of releases (master/dev/releases/tags). But it would be great to pull this update in through composer. I can't because yours is a fork and not on packagist...

Just a side question, why is it that projection libraries (proj4) and shapefile readers are so unpopular in terms of PHP libraries? Just a few people, it seems to me, are working on it, yet I can't imagine so few people need it.

**Comment by nickolanack** [comment]
I think it is because other formats are becoming more common for web based gis systems. For my own projects, I am using this library to convert to kml.

**Comment by coreation** [comment]
That would makes sense yes, however there's an abundance of old GIS layers using all sorts of CRS's unfortunately ;)

**Comment by muka** [comment]
Sure, PR the changes, thanks!

I agree with @nickolanack shp is not the best format to work with. I've used phayes/geoPHP for converting to more useful formats

**Comment by coreation** [comment]
Thanks for the link to the phayes repo, interesting stuff! I'll still need the SHP though, lots of clients want them to be published in GeoJSON, WKT, ... with only a simple configuration ;)
